FROM php:7.4.30-fpm

# Instala dependencias requeridas
RUN apt-get update && apt-get install -y libssl-dev git libonig-dev libzip-dev \
    && apt-get install -y \
    zip \
    unzip \
    p7zip-full \
    && docker-php-ext-install mysqli pdo_mysql mbstring zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

# Instala Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

# Configura el directorio de trabajo y los permisos
WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html


# Expone el puerto 9000 para conectarse con Nginx
EXPOSE 9000

