version: '3'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - my-net

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./start.sh:/var/www/html/start.sh # Agregar script
    networks:
      - my-net
    command: /bin/bash -c "chmod +x /var/www/html/start.sh && /var/www/html/start.sh && php-fpm"

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: miBase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-net

networks:
  my-net:

